FROM ubuntu:20.04

ARG TZ=Europe/Berlin
ARG UID=1000

RUN	apt-get update && \
	# add group / user
	groupadd -r host_dialout && \
	useradd -b /home -m -s /bin/bash -G host_dialout -u $UID user && \
	# set timezone
	DEBIAN_FRONTEND="noninteractive" apt-get install -y tzdata && \
	ln -fs /usr/share/zoneinfo/$TZ /etc/localtime && \
	dpkg-reconfigure --frontend noninteractive tzdata && \
	# deps
	apt-get install -y build-essential git python3 libusb-1.0-0 && \
	# configure python3 as default
	update-alternatives --install /usr/bin/python python /usr/bin/python3 10 && \
	# more deps
	apt-get install -y wget flex bison gperf python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util && \
	#
	apt-get install -y neovim && \
	apt-get clean

USER user

COPY --chown=user:user idf_tools.patch /home/user/

WORKDIR /home/user

RUN	git clone -b v4.2 --recursive https://github.com/espressif/esp-idf.git && \
	patch esp-idf/tools/idf_tools.py < ${HOME}/idf_tools.patch && \
	rm ${HOME}/idf_tools.patch

COPY --chown=user:user --from=build_crosstool /home/user/toolchain /home/user/toolchain/
COPY --chown=user:user --from=build_esp32ulp /home/user/toolchain /home/user/toolchain/

ENV IDF_TOOLS_PATH=/home/user/toolchain
ENV IDF_CCACHE_ENABLE=1

RUN	echo "\n# update PATH" >> .bashrc && \
	echo 'PATH="${HOME}/.local/bin:${PATH}"' >> .bashrc && \
	echo 'PATH="${HOME}/toolchain/xtensa-esp32-elf/bin:${PATH}"' >> .bashrc && \
	echo 'PATH="${HOME}/toolchain/xtensa-esp32s2-elf/bin:${PATH}"' >> .bashrc && \
	echo 'PATH="${HOME}/toolchain/esp32ulp-elf-binutils/bin:${PATH}"' >> .bashrc && \
	echo 'PATH="${HOME}/toolchain/esp32s2ulp-elf-binutils/bin:${PATH}"' >> .bashrc && \
	echo 'PATH="${HOME}/toolchain/openocd-esp32/bin:${PATH}"' >> .bashrc && \
	echo '. ${HOME}/esp-idf/export.sh' >> .bashrc
RUN	esp-idf/tools/idf_tools.py install-python-env && \
	rm -r .cache

USER root

COPY /entrypoint.sh /entry

CMD ["/entry"]
